version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:password@mongo:27017/url-shortener?authSource=admin
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongoDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # Root username for MongoDB
      MONGO_INITDB_ROOT_PASSWORD: password # Root password for MongoDB
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
